CREATE TABLE ProductPersonalization
(
	PersonalizationId BIGINT PRIMARY KEY,
	ProductId INT NOT NULL, --FOREIGN KEY REFERENCES Product
	X INT DEFAULT 0,
	Y INT DEFAULT 0,
	FontSize INT DEFAULT 15,
	Font VARCHAR(100) DEFAULT 'Verdana',
	Color VARCHAR(100) DEFAULT '#FF0000',
	BgColor VARCHAR(100) DEFAULT '#FFFFFF',
	DefaultValue VARCHAR(MAX) NULL,
	Align VARCHAR(100) NULL,
	[Type] VARCHAR(100) NULL,
	IsReadOnly BIT	DEFAULT 0,
	Width INT NULL,
	Height INT NULL,
	IsActive BIT DEFAULT 0
)